<?xml version="1.0" encoding="utf-8"?><Database Name="UTF" Class="SystemWebDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=plumeria.arvixe.com;Initial Catalog=UTF;Integrated Security=False;User ID=sys_login" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="UTFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Carico" Member="Carico">
    <Type Name="Carico">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pvID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Ordine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cData" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Documento" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Numero" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="rData" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Emittente" Type="System.String" DbType="NVarChar(42)" CanBeNull="true" />
      <Column Name="Benzina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gasolio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="yearId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Year_Carico" Member="Year" ThisKey="yearId" OtherKey="yearId" Type="Year" IsForeignKey="true" />
      <Association Name="Pv_Carico" Member="Pv" ThisKey="pvID" OtherKey="pvID" Type="Pv" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Year" Member="Year">
    <Type Name="Year">
      <Column Name="yearId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Anno" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Year_Carico" Member="Carico" ThisKey="yearId" OtherKey="yearId" Type="Carico" />
    </Type>
  </Table>
  <Table Name="dbo.Pv" Member="Pv">
    <Type Name="Pv">
      <Column Name="pvID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pvName" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="pvFlagId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Pv_Carico" Member="Carico" ThisKey="pvID" OtherKey="pvID" Type="Carico" />
      <Association Name="Pv_PvTank" Member="PvTank" ThisKey="pvID" OtherKey="pvID" Type="PvTank" />
      <Association Name="Flag_Pv" Member="Flag" ThisKey="pvFlagId" OtherKey="pvFlagId" Type="Flag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Flag" Member="Flag">
    <Type Name="Flag">
      <Column Name="pvFlagId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Descrizione" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Flag_Pv" Member="Pv" ThisKey="pvFlagId" OtherKey="pvFlagId" Type="Pv" />
    </Type>
  </Table>
  <Table Name="dbo.PvCali" Member="PvCali">
    <Type Name="PvCali">
      <Column Name="PvCaliId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PvTankId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FieldDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PvTank_PvCali" Member="PvTank" ThisKey="PvTankId" OtherKey="PvTankId" Type="PvTank" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PvTank" Member="PvTank">
    <Type Name="PvTank">
      <Column Name="PvTankId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pvID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Modello" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="LastDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Capienza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Giacenza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PvTank_PvCali" Member="PvCali" ThisKey="PvTankId" OtherKey="PvTankId" Type="PvCali" />
      <Association Name="Pv_PvTank" Member="Pv" ThisKey="pvID" OtherKey="pvID" Type="Pv" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_PvTank" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Peso" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Prezzo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Product_PvTank" Member="PvTank" ThisKey="ProductId" OtherKey="ProductId" Type="PvTank" />
    </Type>
  </Table>
</Database>