// <auto-generated />
namespace SystemWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15));
        
        string IMigrationMetadata.Id
        {
            get { return "201603230822222_15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
