// <auto-generated />
namespace GestioniDirette.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18));
        
        string IMigrationMetadata.Id
        {
            get { return "201705231332104_18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
